/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTrendsRouteImport } from './routes/dashboard.trends'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPredictionsRouteImport } from './routes/dashboard.predictions'
import { Route as DashboardOffendersRouteImport } from './routes/dashboard.offenders'
import { Route as DashboardNetworkRouteImport } from './routes/dashboard.network'
import { Route as DashboardMapRouteImport } from './routes/dashboard.map'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard.alerts'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrendsRoute = DashboardTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPredictionsRoute = DashboardPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOffendersRoute = DashboardOffendersRouteImport.update({
  id: '/offenders',
  path: '/offenders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNetworkRoute = DashboardNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMapRoute = DashboardMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/network': typeof DashboardNetworkRoute
  '/dashboard/offenders': typeof DashboardOffendersRoute
  '/dashboard/predictions': typeof DashboardPredictionsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trends': typeof DashboardTrendsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/network': typeof DashboardNetworkRoute
  '/dashboard/offenders': typeof DashboardOffendersRoute
  '/dashboard/predictions': typeof DashboardPredictionsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trends': typeof DashboardTrendsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/network': typeof DashboardNetworkRoute
  '/dashboard/offenders': typeof DashboardOffendersRoute
  '/dashboard/predictions': typeof DashboardPredictionsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trends': typeof DashboardTrendsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/alerts'
    | '/dashboard/map'
    | '/dashboard/network'
    | '/dashboard/offenders'
    | '/dashboard/predictions'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/trends'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/signup'
    | '/dashboard/alerts'
    | '/dashboard/map'
    | '/dashboard/network'
    | '/dashboard/offenders'
    | '/dashboard/predictions'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/trends'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/alerts'
    | '/dashboard/map'
    | '/dashboard/network'
    | '/dashboard/offenders'
    | '/dashboard/predictions'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/trends'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trends': {
      id: '/dashboard/trends'
      path: '/trends'
      fullPath: '/dashboard/trends'
      preLoaderRoute: typeof DashboardTrendsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/predictions': {
      id: '/dashboard/predictions'
      path: '/predictions'
      fullPath: '/dashboard/predictions'
      preLoaderRoute: typeof DashboardPredictionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/offenders': {
      id: '/dashboard/offenders'
      path: '/offenders'
      fullPath: '/dashboard/offenders'
      preLoaderRoute: typeof DashboardOffendersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/network': {
      id: '/dashboard/network'
      path: '/network'
      fullPath: '/dashboard/network'
      preLoaderRoute: typeof DashboardNetworkRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/map': {
      id: '/dashboard/map'
      path: '/map'
      fullPath: '/dashboard/map'
      preLoaderRoute: typeof DashboardMapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardMapRoute: typeof DashboardMapRoute
  DashboardNetworkRoute: typeof DashboardNetworkRoute
  DashboardOffendersRoute: typeof DashboardOffendersRoute
  DashboardPredictionsRoute: typeof DashboardPredictionsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTrendsRoute: typeof DashboardTrendsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardMapRoute: DashboardMapRoute,
  DashboardNetworkRoute: DashboardNetworkRoute,
  DashboardOffendersRoute: DashboardOffendersRoute,
  DashboardPredictionsRoute: DashboardPredictionsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTrendsRoute: DashboardTrendsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
